### ISSUE TITLE
Add cleaned Canterbury news stories text files 

### ISSUE THREAD

**Issue by sonicquilt** [UW-Rice-CRISP/Objective1#2]
@lucylin I created a directory /TextData/CanterburyNewsStoriesCleaned/ to put them in. If you'd prefer a different organization structure, feel free to set up your own. (If you can't add folders etc., let me know so I can sort out permissions.)

**Comment by lucylin** [comment]
Perfect, thanks - in the process of porting things over / cleaning up my
notes; will let you know if I have trouble pushing changes.

On Thursday, October 29, 2015, Scott Miles notifications@github.com wrote:

> @lucylin https://github.com/lucylin I created a directory
> /TextData/CanterburyNewsStoriesCleaned/ to put them in. If you'd prefer a
> different organization structure, feel free to set up your own. (If you
> can't add folders etc., let me know so I can sort out permissions.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Rice-CRISP/Objective1/issues/2.

## 

-- Lucy

(please excuse typos - this message was written using only thumbs)

**Comment by lucylin** [comment]
Done with ccbd9dc. (Only organizational change is to remove the readme from the directory with the news stories - it's easier to process the directory with the assumption that the only files there are news .txt ones.)

**Comment by sonicquilt** [comment]
Ah. Good point! I guess there's not a like button on Github... hah.
