### ISSUE TITLE
Do a basic text analysis (e.g. word counts) of infrastructure terms across the news articles

### ISSUE THREAD

**Issue by lucylin** [UW-Rice-CRISP/Objective1#4]

**Comment by sonicquilt** [comment]
@lucylin I put a quick Jupyter notebook in the repository showing NLTK, if you're interested. Obviously lots more can be done with it. It's pretty useful and fairly well documented. (Some hacks in it though -- like hard coded plotting arguments.)

https://github.com/UW-Rice-CRISP/Objective1/tree/master/CodeExamples

**Comment by sonicquilt** [comment]
If you click on the ipynb file it will render the notebook in place.

**Comment by lucylin** [comment]
Added the word counts that I was referring to during today's meeting. I can figure out computing the doc frequency (tf-idf) thing Noah was talking about, but it won't be until tomorrow afternoon (post ML midterm!).

**Comment by sonicquilt** [comment]
Sounds good. It'd be quick to use the NLTK notebook I put up to do a dispersion diagram for the whole corpus. But not sure it's worth it--there may not be enough instances relative to the overall length of the corpus for it to reveal much. But eventually I'll do it if you don't for the hell of it!
